### ISSUE TITLE
as a trigger rule `products` param in hysds-io returns a string instead of a one-item list

### ISSUE THREAD

**Issue by pymonger** [hysds/multi_acquisition_localizer#1]
From a trigger rule, it fails with:

```
##########################################
Running multi_acquisition_localizer.py on : Fri Nov 16 10:07:18 UTC 2018
Finished running  multi_acquisition_localizer.py: Fri Nov 16 10:07:19 UTC 2018
Failed to run  multi_acquisition_localizer.py.
[2018-11-16 10:07:19,193: INFO sling_acquisitions.py:resolve_source] Acq List Type : <type 'unicode'>
[2018-11-16 10:07:19,193: INFO sling_acquisitions.py:get_acq_data_from_list] get_acq_data_from_list
{'query': {'term': {'_id': u'a'}}, 'partial_fields': {'partial': {'exclude': 'city'}}}
0
Traceback (most recent call last):
  File "/home/ops/verdi/ops/multi_acquisition_localizer/multi_acquisition_localizer.py", line 15, in <module>
    sys.exit(main())
  File "/home/ops/verdi/ops/multi_acquisition_localizer/multi_acquisition_localizer.py", line 13, in main
    sling_acquisitions.resolve_source(context_file)    
  File "/home/ops/verdi/ops/multi_acquisition_localizer/sling_acquisitions.py", line 308, in resolve_source
    acq_info = get_acq_data_from_list(acq_list)
  File "/home/ops/verdi/ops/multi_acquisition_localizer/sling_acquisitions.py", line 256, in get_acq_data_from_list
    acq_data = util.get_partial_grq_data(acq)['fields']['partial'][0] 
  File "/home/ops/verdi/ops/multi_acquisition_localizer/util.py", line 122, in get_partial_grq_data
    return result['hits']['hits'][0]
IndexError: list index out of range
```

The context.json shows:

```
{
  "_command": "/home/ops/verdi/ops/multi_acquisition_localizer/multi_acquisition_localizer.sh", 
  "asf_ngap_download_queue": "factotum-job_worker-asf_throttled", 
  "container_image_id": "sha256:3c4c2bc989c9de3255bcd496241881f83eb1f995477e45dad0a73d77c46247e3", 
  "container_image_name": "container-earthobservatory_multi_acquisition_localizer:master", 
  "container_image_url": "s3://s3-ap-southeast-1.amazonaws.com/ntu-hysds-code/container-earthobservatory_multi_acquisition_localizer:master.tar.gz", 
  "container_mappings": {
    "/home/ops/.aws": [
      "/home/ops/.aws", 
      "ro"
    ], 
    "/home/ops/.netrc": [
      "/home/ops/.netrc"
    ], 
    "/home/ops/verdi/etc/settings.conf": "/home/ops/verdi/ops/multi_acquisition_localizer/settings.conf"
  }, 
  "container_specification": {
    "digest": "sha256:3c4c2bc989c9de3255bcd496241881f83eb1f995477e45dad0a73d77c46247e3", 
    "id": "container-earthobservatory_multi_acquisition_localizer:master", 
    "url": "s3://s3-ap-southeast-1.amazonaws.com/ntu-hysds-code/container-earthobservatory_multi_acquisition_localizer:master.tar.gz", 
    "version": "master"
  }, 
  "esa_download_queue": "factotum-job_worker-scihub_throttled", 
  "job_priority": 0, 
  "job_specification": {
    "command": "/home/ops/verdi/ops/multi_acquisition_localizer/multi_acquisition_localizer.sh", 
    "container": "container-earthobservatory_multi_acquisition_localizer:master", 
    "id": "job-acquisition_localizer_multi:master", 
    "imported_worker_files": {
      "/home/ops/.aws": [
        "/home/ops/.aws", 
        "ro"
      ], 
      "/home/ops/.netrc": [
        "/home/ops/.netrc"
      ], 
      "/home/ops/verdi/etc/settings.conf": "/home/ops/verdi/ops/multi_acquisition_localizer/settings.conf"
    }, 
    "job-version": "master", 
    "params": [
      {
        "destination": "context", 
        "name": "asf_ngap_download_queue", 
        "value": "factotum-job_worker-asf_throttled"
      }, 
      {
        "destination": "context", 
        "name": "esa_download_queue", 
        "value": "factotum-job_worker-scihub_throttled"
      }, 
      {
        "destination": "context", 
        "name": "spyddder_extract_version", 
        "value": "beta_20181113"
      }, 
      {
        "destination": "context", 
        "name": "products", 
        "value": "acquisition-S1A_IW_SLC__1SDV_20181019T090410_20181019T090437_024202_02A5CD_FA67"
      }
    ], 
    "resource": "jobspec", 
    "soft_time_limit": 86400, 
    "time_limit": 87000
  }, 
  "localize_urls": [], 
  "products": "acquisition-S1A_IW_SLC__1SDV_20181019T090410_20181019T090437_024202_02A5CD_FA67", 
  "spyddder_extract_version": "beta_20181113", 
  "tag": "test_multi_acq_scraper"
}
```

Find out the right incantation for `hysds-io`.

**Comment by pymonger** [comment]
Fixed: https://github.com/hysds/multi_acquisition_localizer/commit/390208174fffc5701c0143220dfd0ab652f346b6.
